arrowParens: avoid
bracketSpacing: true
endOfLine: auto
printWidth: 120
singleQuote: false
tabWidth: 2
useTabs: false
trailingComma: all

plugins:
  - "prettier-plugin-solidity"

overrides:
  - files: "*.sol"
    options:
      compiler: "0.8.24"
      tabWidth: 4
